### PR TITLE
Updated all dependencies

### PR DESCRIPTION
**Pull request by enyo**

### CODE REVIEW

**Comment by jimsimon** [comment]
Do you mind removing the version bump and changelog from this patch?  I prefer to put the version bump on a separate commit, and the changelog is out of date (I'll generate one when I do the release).

**Comment by enyo** [comment]
Done

**Comment by jimsimon** [comment]
Thanks for the contribution!  I'll most likely be putting a release out tonight.

**Comment by jimsimon** [comment]
Version 3.0.3 has been released with this change included.

**Pull request merged**
